version: '3'

services:
  wai:
    build: 
      context: .
      args: 
        - NODE_ENV=development
    volumes:
      - .:/home/node/wai
      - /home/node/wai/node_modules
    ports:
      - ${APP_PORT}:8000
      - ${APP_DEBUG_PORT}:9229
    environment:
      - TOKEN=token_dev
    command: npm start
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - /data/wai-data:/data/db
    ports:
      - ${DB_PORT}:27017