version: '3'

services:
  app:
    container_name: app
    build:
      context: .
      args: 
        - NODE_ENV=development
    volumes:
      - ./:/home/node/wai
      - /home/node/wai/node_modules
    ports:
      - ${APP_PORT}:8000
      - 443:443
      - ${APP_DEBUG_PORT}:9229
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - wai-data:/data/db
    ports:
      - ${DB_PORT}:27017

volumes:
  wai-data: